name: Package VSCode Extension

on:
  push:
    tags:
      - 'v*.*.*' # Trigger on version tags

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Lint and Test
        run: npm run lint && npm test
      - name: pre package
        run: npm run vscode:prepublish

      - name: Package Extension
        run: vsce package

      - name: Upload Extension Package
        uses: actions/upload-artifact@v2
        with:
          name: vscode-extension
          path: '*.vsix'
